# This file has been autogenerated by the pywayland scanner

# Copyright © 2025 Fl0w
#
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
# list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

from __future__ import annotations

import enum

from pywayland.protocol_core import Argument, ArgumentType, Global, Interface, Proxy, Resource


class HyprlandInputCaptureManagerV1(Interface):
    """Manage input capture sessions

    This interface allows to create an input capture session.
    """

    name = "hyprland_input_capture_manager_v1"
    version = 2


class HyprlandInputCaptureV1(Interface):
    """Close reproduction of the xdg input capture portal

    Interface that is used to create barrier, and trigger capture and release
    of the pointer. The inputs are sent through an EIS socket, when the cursor
    hit a barrier. Barriers can only be placed on screen edges and need to be a
    straight line that cover one corner to another.
    """

    name = "hyprland_input_capture_v1"
    version = 2

    class error(enum.IntEnum):
        invalid_barrier_id = 0
        invalid_barrier = 1
        invalid_activation_id = 2


class HyprlandInputCaptureManagerV1Resource(Resource[HyprlandInputCaptureManagerV1]):
    interface = HyprlandInputCaptureManagerV1


class HyprlandInputCaptureV1Resource(Resource[HyprlandInputCaptureV1]):
    interface = HyprlandInputCaptureV1

    @HyprlandInputCaptureV1.event(
        Argument(ArgumentType.FileDescriptor),
    )
    def eis_fd(self, fd: int) -> None:
        """Eis file descriptor

        This event provide the file descriptor of an eis socket where inputs
        will be sent when input capturing is active

        :param fd:
            eis socket file descriptor
        :type fd:
            `ArgumentType.FileDescriptor`
        """
        self._post_event(0, fd)

    @HyprlandInputCaptureV1.event()
    def disabled(self) -> None:
        """Disable the session

        Called when the application will not receive captured input. The
        application can call enable to request future input capturing
        """
        self._post_event(1)

    @HyprlandInputCaptureV1.event(
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Fixed),
        Argument(ArgumentType.Fixed),
        Argument(ArgumentType.Uint),
    )
    def activated(self, activation_id: int, x: float, y: float, barrier_id: int) -> None:
        """Inputs has been captured

        Called when the application is about to receive inputs

        :param activation_id:
            Same number used in eis start_emulating to allow synchronisation
        :type activation_id:
            `ArgumentType.Uint`
        :param x:
            the x position of the cursor
        :type x:
            `ArgumentType.Fixed`
        :param y:
            the y position of the cursor
        :type y:
            `ArgumentType.Fixed`
        :param barrier_id:
            the is of the barrier that have been triggered
        :type barrier_id:
            `ArgumentType.Uint`
        """
        self._post_event(2, activation_id, x, y, barrier_id)

    @HyprlandInputCaptureV1.event(
        Argument(ArgumentType.Uint),
    )
    def deactivated(self, activation_id: int) -> None:
        """Pointer motion

        Called when input capture is stopped, and inputs are no longer sent to
        the application

        :param activation_id:
            same activation id of the latest activated event
        :type activation_id:
            `ArgumentType.Uint`
        """
        self._post_event(3, activation_id)


class HyprlandInputCaptureManagerV1Proxy(Proxy[HyprlandInputCaptureManagerV1]):
    interface = HyprlandInputCaptureManagerV1

    @HyprlandInputCaptureManagerV1.request(
        Argument(ArgumentType.NewId, interface=HyprlandInputCaptureV1),
        Argument(ArgumentType.String),
    )
    def create_session(self, handle: str) -> HyprlandInputCaptureV1Proxy:
        """Create a input capture session

        Create a input capture session.

        :param handle:
        :type handle:
            `ArgumentType.String`
        :returns:
            :class:`~pywayland.protocol.hyprland_input_capture_v1.HyprlandInputCaptureV1`
        """
        session = self._marshal_constructor(0, HyprlandInputCaptureV1, handle)
        return session


class HyprlandInputCaptureV1Proxy(Proxy[HyprlandInputCaptureV1]):
    interface = HyprlandInputCaptureV1

    @HyprlandInputCaptureV1.request()
    def clear_barriers(self) -> None:
        """Clear every barriers registered

        Remove every barriers from the session, new barriers need to be send
        before calling enable again.
        """
        self._marshal(0)

    @HyprlandInputCaptureV1.request(
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Uint),
    )
    def add_barrier(self, zone_set: int, id: int, x1: int, y1: int, x2: int, y2: int) -> None:
        """Add one barrier

        Add one barrier to the current session, the barrier need to a line
        placed on the edge of the screen, and is a straight line from one
        corner to another.

        :param zone_set:
            The current zone_set
        :type zone_set:
            `ArgumentType.Uint`
        :param id:
            The zone id
        :type id:
            `ArgumentType.Uint`
        :param x1:
        :type x1:
            `ArgumentType.Uint`
        :param y1:
        :type y1:
            `ArgumentType.Uint`
        :param x2:
        :type x2:
            `ArgumentType.Uint`
        :param y2:
        :type y2:
            `ArgumentType.Uint`
        """
        self._marshal(1, zone_set, id, x1, y1, x2, y2)

    @HyprlandInputCaptureV1.request()
    def enable(self) -> None:
        """Enable input capturing

        Enable the input capturing to be triggered by the cursor crossing a
        barrier.
        """
        self._marshal(2)

    @HyprlandInputCaptureV1.request()
    def disable(self) -> None:
        """Disable input capturing

        Disable input capturing, the crossing of a barrier will not trigger
        anymore input capture.
        """
        self._marshal(3)

    @HyprlandInputCaptureV1.request(
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Fixed),
        Argument(ArgumentType.Fixed),
    )
    def release(self, activation_id: int, x: float, y: float) -> None:
        """Release input capturing

        Release input capturing, the input are not intercepted anymore and
        barrier crossing will activate it again.     If x != -1 and y != -1
        then the cursor is warped to the x and y coordinates.

        :param activation_id:
            The activation id provided when activated is called
        :type activation_id:
            `ArgumentType.Uint`
        :param x:
            the x position of the cursor
        :type x:
            `ArgumentType.Fixed`
        :param y:
            the y position of the cursor
        :type y:
            `ArgumentType.Fixed`
        """
        self._marshal(4, activation_id, x, y)

    @HyprlandInputCaptureV1.request(version=2)
    def destroy(self) -> None:
        """Destroy the session

        Destroy the input capture session.

        Any barriers registered by this session are removed, input capturing is
        stopped, and the eis socket associated with this session is closed by
        the compositor. The client must not use the object after this request.
        """
        self._marshal(5)
        self._destroy()


class HyprlandInputCaptureManagerV1Global(Global[HyprlandInputCaptureManagerV1]):
    interface = HyprlandInputCaptureManagerV1


class HyprlandInputCaptureV1Global(Global[HyprlandInputCaptureV1]):
    interface = HyprlandInputCaptureV1


HyprlandInputCaptureManagerV1._gen_c()
HyprlandInputCaptureManagerV1.proxy_class = HyprlandInputCaptureManagerV1Proxy
HyprlandInputCaptureManagerV1.resource_class = HyprlandInputCaptureManagerV1Resource
HyprlandInputCaptureManagerV1.global_class = HyprlandInputCaptureManagerV1Global


HyprlandInputCaptureV1._gen_c()
HyprlandInputCaptureV1.proxy_class = HyprlandInputCaptureV1Proxy
HyprlandInputCaptureV1.resource_class = HyprlandInputCaptureV1Resource
HyprlandInputCaptureV1.global_class = HyprlandInputCaptureV1Global
